using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NCast.Devices.Chromecast.Entities
{
    public enum SetupState
    {
        SETUP_STATE_UNKNOWN = 0,
        SETUP_STATE_DISCONNECTED = 10,
        SETUP_STATE_DISCONNECTED_EXTERNAL_CLIENT_ACCESSED = 11,
        SETUP_STATE_SCANNING = 20,
        SETUP_STATE_SCANNING_WRONG_SSID = 21,
        SETUP_STATE_BEING_CONFIGURED = 30,
        SETUP_STATE_BEING_CONFIGURED_WRONG_PASSWORD = 31,
        SETUP_STATE_POSSIBLY_WRONG_PASSWORD = 32,
        SETUP_STATE_OBTAINING_IP_ADDRESS = 40,
        SETUP_STATE_OBTAINING_IP_ADDRESS_BAD_AP = 41,
        SETUP_STATE_CHECKING_GLOBAL_CONNECTIVITY = 50,
        SETUP_STATE_CHECKING_GLOBAL_CONNECTIVITY_BAD_ROUTER = 51,
        SETUP_STATE_CONNECTED = 60,
        SETUP_STATE_CONNECTED_NO_WIFI_SAVED = 61,
        SETUP_STATE_CONNECTED_UPDATE_ONLY = 62,
    }

}
