using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

namespace NCast.Devices.Chromecast.Entities.Response
{//------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.
 //     Runtime Version:4.0.30319.19455
 //
 //     Changes to this file may cause incorrect behavior and will be lost if
 //     the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------



    [DataContract]
    public partial class AppListRoot
    {

        [DataMember()]
        public ChromecastApp[] applications;

        [DataMember()]
        public string[] enabled_app_ids;

        [DataMember()]
        public Configuration configuration;
    }

    [DataContract(Name = "applications")]
    public partial class ChromecastApp
    {

        [DataMember(Name = "use_channel")]
        public bool use_channel;

        [DataMember(Name = "allow_empty_post_data")]
        public bool allow_empty_post_data;

        [DataMember(Name = "app_id")]
        public string AppId;

        [DataMember(Name = "url")]
        public string url;

        [DataMember(Name = "dial_enabled")]
        public bool dial_enabled;

        [DataMember(Name = "allow_restart")]
        public bool allow_restart;

        [DataMember(Name = "external")]
        public bool external;

        [DataMember(Name = "native_app")]
        public bool native_app;

        [DataMember(Name = "dial_info")]
        public string dial_info;

        [DataMember(Name = "command_line")]
        public string command_line;

        [DataMember(Name = "display_name")]
        public string display_name;

        [DataMember(Name = "uses_ipc")]
        public bool uses_ipc;

        [DataMember(Name = "resolution_height")]
        public int resolution_height;

        public override string ToString()
        {
            return display_name != null ? display_name : AppId;
        }
    }

    [DataContract(Name = "configuration")]
    public partial class Configuration
    {

        [DataMember()]
        public string idle_screen_app;
    }

}
